try:
    print(x)
except:
    print("An error ocurred")
finally:
    print("Success")
